// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB01CXk2_685ifOsEik2sMuAzzmNkloIBU',
    appId: '1:243707806517:ios:8485d1e587319887f1427c',
    messagingSenderId: '243707806517',
    projectId: 'mab-fyp',
    storageBucket: 'mab-fyp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB01CXk2_685ifOsEik2sMuAzzmNkloIBU',
    appId: '1:243707806517:ios:8485d1e587319887f1427c',
    messagingSenderId: '243707806517',
    projectId: 'mab-fyp',
    storageBucket: 'mab-fyp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_3HguFxAG6MI3oaHLa84uLaxisPp9PJg',
    appId: '1:243707806517:web:e3a5ad58592ec6d4f1427c',
    messagingSenderId: '243707806517',
    projectId: 'mab-fyp',
    authDomain: 'mab-fyp.firebaseapp.com',
    storageBucket: 'mab-fyp.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_3HguFxAG6MI3oaHLa84uLaxisPp9PJg',
    appId: '1:243707806517:web:e3a5ad58592ec6d4f1427c',
    messagingSenderId: '243707806517',
    projectId: 'mab-fyp',
    authDomain: 'mab-fyp.firebaseapp.com',
    storageBucket: 'mab-fyp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA68fu6-TsdAo05rh7S4VAJx1uP83_OuXM',
    appId: '1:243707806517:android:eae273e6b6c7ebe1f1427c',
    messagingSenderId: '243707806517',
    projectId: 'mab-fyp',
    storageBucket: 'mab-fyp.firebasestorage.app',
  );

}